# Generated by Django 5.1 on 2024-09-12 18:43

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
    ]
