# Generated by Django 5.1 on 2024-09-17 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2024, 9, 17, 12, 13, 9, 56678))),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
